language: php

matrix:
  include:
    - php: 7.1
      env: dependencies=highest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=highest
    - php: 7.1
      env: dependencies=lowest

install:
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --prefer-dist; fi
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction --prefer-dist; fi

script:
  - vendor/bin/phpunit tests

cache:
  directories:
    - $HOME/.composer/cache/files
